2023-09-28 17:11:58,384 ERROR EShop.Middleware.CustomExceptionMiddleware.ExceptionMiddleware.MoveNext [28] - MESSAGE: Something went wrong: System.NullReferenceException: Object reference not set to an instance of an object.
   at EShop.Infrastracture.Persistence.DBHandler.DatabaseHandler.Execute[T](String sp, List`1 data, CommandType commandType) in D:\Barnabas\Projects\API\EShop\EShop.Infrastracture\Persistence\DBHandler\DatabaseHandler.cs:line 55
   at EShop.Infrastracture.Persistence.Commands.CreateCartCommandHandler.Handle(CreateCartCommand command, CancellationToken cancellationToken) in D:\Barnabas\Projects\API\EShop\EShop.Infrastracture\Persistence\Commands\CreateCartCommandHandler.cs:line 43
   at EShop.Application.Services.CartService.CreateCart(AddCartRequest addCartRequest) in D:\Barnabas\Projects\API\EShop\EShop.Application\Services\CartService.cs:line 23
   at EShop.Controllers.CartController.CreateCart(AddCartRequest addCartRequest) in D:\Barnabas\Projects\API\EShop\EShop\Controllers\CartController.cs:line 38
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at EShop.Middleware.CustomExceptionMiddleware.ExceptionMiddleware.InvokeAsync(HttpContext httpContext) in D:\Barnabas\Projects\API\EShop\EShop\Middleware\CustomExceptionMiddleware\ExceptionMiddleware.cs:line 19
